version: '3.0'

services:
  bot:
    image: menshikovas/random_coffee_bot:latest
    working_dir: /bot
    volumes:
      - /mnt/e/DEV/random/db:/bot/db
      - /mnt/e/DEV/random/log:/bot/logs
    restart: always
    env_file: /mnt/e/DEV/private/random_coffee/data/.env
